using _Code.Scripts.Rooms;
using UnityEngine;
using Interactions;
using System;
using System.Collections.Generic;
using UnityEditor;

namespace Rooms
{
    [Serializable]
    public class RoomRotatorEntry
    {
        public Room room;
        public float rotationDegree = 90f;
        public float rotationTime = 1.2f;
        public Vector3 rotatorVector = new(0, 1, 0);
        public float cancelSpeedMultiplier = 2f;
    }

    public class RoomRotator : MonoBehaviour, IHoldInteractable
    {
        [SerializeField] private List<RoomRotatorEntry> targetRooms = new();
        [SerializeField] private MeshFilter hologramTarget;
        [SerializeField] private bool saveHologramMeshAsset;

        private IInteractor _currentInteractor;
        public GameObject GameObject => gameObject;

        public void Awake()
        {
            Debug.Log($"RoomRotator Awake: targetRooms count = {targetRooms.Count}");
            if (targetRooms.Count == 0)
                Debug.LogWarning("RoomRotator does not have any targetRooms", this);
            if (hologramTarget == null)
                Debug.LogWarning("RoomRotator does not have a hologramPivot", this);
            else if (hologramTarget.sharedMesh == null && targetRooms.Count > 0)
            {
                Debug.Log("HologramTarget.sharedMesh is null, attempting to create on Awake.");
                CreateHologramMesh(0, saveHologramMeshAsset);
            }
        }

        public void CreateHologramMesh(int roomIndex = 0, bool saveAsset = false, bool makeNewInstance = true, bool optimize = false)
        {
            Debug.Log($"CreateHologramMesh called: roomIndex={roomIndex}, saveAsset={saveAsset}");
            var firstRoom = (roomIndex >= 0 && roomIndex < targetRooms.Count) ? targetRooms[roomIndex].room : null;
            if (firstRoom == null)
            {
                Debug.LogWarning($"Room at index {roomIndex} is null.");
                return;
            }

            var meshFilters = firstRoom.gameObject.GetComponentsInChildren<MeshFilter>();
            if (meshFilters.Length == 0)
            {
                Debug.LogWarning("No MeshFilters found in room: " + firstRoom.name);
                return;
            }
            
            List<CombineInstance> combineList = new List<CombineInstance>();
            for (int i = 0; i < meshFilters.Length; i++)
            {
                if (meshFilters[i].sharedMesh == null) continue;
                
                CombineInstance combine = new CombineInstance();
                combine.mesh = meshFilters[i].sharedMesh;
                combine.transform = firstRoom.transform.worldToLocalMatrix * meshFilters[i].transform.localToWorldMatrix;
                combineList.Add(combine);
            }

            if (combineList.Count == 0)
            {
                Debug.LogWarning("No meshes to combine in room: " + firstRoom.name);
                return;
            }

            var mesh = new Mesh();
            mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
            mesh.CombineMeshes(combineList.ToArray(), true, true);
            Debug.Log($"Meshes combined. Vertex count: {mesh.vertexCount}");

            var center = mesh.bounds.center;
            var verts = mesh.vertices;
            for (int i = 0; i < verts.Length; i++)
                verts[i] -= center;
            mesh.vertices = verts;
            mesh.RecalculateBounds();
            mesh.RecalculateNormals();

            if (optimize) mesh.Optimize();

            if (hologramTarget != null)
            {
                hologramTarget.sharedMesh = mesh;
                hologramTarget.transform.rotation = firstRoom.transform.rotation;
            }

        #if UNITY_EDITOR
            if (saveAsset)
            {
                Debug.Log($"Saving mesh for room index {roomIndex}...");
                SaveMesh(mesh, firstRoom.name + "_Hologram", makeNewInstance);
            }
        #endif

            Debug.Log("Hologram mesh created");
        }

    #if UNITY_EDITOR
        public void SaveMesh(Mesh mesh, string meshName, bool makeNewInstance)
        {
            Debug.Log($"SaveMesh called for {meshName}");
            string directoryPath = "Assets/Resources/Meshes/Autogenerated/";

            if (!System.IO.Directory.Exists(directoryPath))
            {
                System.IO.Directory.CreateDirectory(directoryPath);
                AssetDatabase.Refresh();
            }

            string fullPath = directoryPath + meshName + ".asset";
            fullPath = AssetDatabase.GenerateUniqueAssetPath(fullPath);
            Debug.Log($"Saving mesh to fullPath: {fullPath}");

            Mesh meshToSave = (makeNewInstance) ? Instantiate(mesh) : mesh;

            AssetDatabase.CreateAsset(meshToSave, fullPath);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("Mesh saved to: " + fullPath);
        }
    #endif

        public void RotateRoom()
        {
            foreach (var entry in targetRooms)
                entry.room?.StartRotate(entry.rotationDegree, entry.rotationTime, entry.rotatorVector, entry.cancelSpeedMultiplier);
        }

        public void Interact(IInteractor interactor) => OnHoldStarted(interactor);

        public void OnHoldStarted(IInteractor interactor)
        {
            if (_currentInteractor != null && _currentInteractor != interactor) return;
            _currentInteractor = interactor;
            RotateRoom();
            _currentInteractor = null;
        }

        public void OnHoldCanceled(IInteractor interactor)
        {
            if (_currentInteractor != null && _currentInteractor != interactor) return;
            foreach (var entry in targetRooms)
                entry.room?.CancelRotate();
            _currentInteractor = null;
        }

        public void OnHoldCompleted(IInteractor interactor)
        {
            if (_currentInteractor != null && _currentInteractor != interactor) return;
            _currentInteractor = null;
        }
    }
}